FreeCAD/FPA

- statutes.md
This is probably not all. I have only read it quickly.
> Some Typos

- FPADF_Announcement.md
An announcement of FPADF and description of process.  re issue #24
> [FPADF] Announcement

- handbook/corporate/AISBL/links.md
3 useful URLs.  2 English/French accounting glossaries and the Belgian accounting standards group's rules for simplified accounting for AIBSLs.
> [AISBL]Add some URLs

- index.md
broken link in contact section of main page
> fix broken link

- drafts/FPAAnnualReport2022.md
Mostly minor typos and some grammatical smoothing.
> First round of notes from @chennes

- drafts/FPAAnnualReport2022.md
Added items under 2023 plan. Initially thought about making two separate files, but not sure it's really needed...
> Added 2023 plan

- drafts/FPAAnnualReport2022.md
- apply comments to recent update
- remove references to separate 2023 plan document
> [AnnualReport]apply comments from @chennes

- reports/2023_09_27_Prokoudine.md
Late fixes from Pieter Hijma. Pieter, please review and comment.
> Update grant research report

- handbook/people/roster.md
[Reference](https://forum.freecad.org/viewtopic.php?p=715101#p715101)
> Move ickby to inactive status

- _programs/FOSDEM_travel_grants.md
- _programs/FPADF_Announcement.md
- _programs/FreeCAD_day_2023.md
- _programs/blog_content.md
- _reports/2022.md
- assets/css/styles.scss
- budgets/2022.md
- handbook/corporate/AISBL/mandatory_tasks.md
- handbook/people/roster.md
- handbook/process/bookkeeping/gnuCashToGithubMarkdown.md
- handbook/process/reconfirmation.md
- handbook/process/rules.md
- index.md
- programs.md
- reports/2023_09_27_Prokoudine.md
Hi there !
Following Benjamin's (@benj5378) website modifications, here are a few further updates to its appearance.
Namely:
- CSS style cleanup, remove duplicates and unused classes
- less "flashy" colors (blue and pink) with shades of blue
- harmonize some texts, headings, sizes, margins, justification
- a few horizontal separators (rules) to make sections easier to read
- a few errors or link corrections here and there
<details>
<summary><b>Click here for a few screenshots</b></summary>
---
---
---
---
---
---
---
</details>
> FPA website style update and cleanup

- annualreports/2024/2024.md
Merged report draft (Yorik's part)
> Merged 2024 annual report

- annualreports/2024/2024.md
> fix links to wrong chart file name

- _programs/learning_initiative.md
- programs.md
Launching a page to the FPA initiatives to start thinking of a "learning project"
> Added learning initiative page

- handbook/index.md
- handbook/process/grant-program-rules.md
Comes with a placeholder for the URL where the git repository for grant applications will be.
> Add grant program rules, 1st iteration

- _programs/FPADF_Announcement.md
- _programs/grant-program-archive.md
- handbook/process/grant-program-rules.md
This PR adds the new program page that replaces the existing one, updates the list of ongoing grant projects, and adds a new page that serves as the grants archive for past project.
TODO:
> Update the grant program page

- _programs/managing-grant-program.md
- handbook/index.md
We can (and likely will) refine this as we go.
> Add first shot at the grant program management guide

- annualreports/2024/2024.md
> minor edits

- _reports/2024.md
added second hyphens.
@WandererFan
> Update dead links in 2024.md

- handbook/process/bookkeeping/FPADFGrants.md~
- handbook/process/bookkeeping/GrantsContractsVAT.md
- handbook/process/bookkeeping/GrantsContractsVat.md~
mostly a placeholder, but some links to grant and vat explanations...
> add notes on grants & vat

- handbook/process/bookkeeping/GrantsContractsVAT.md
Add links to new contract/mou docs
> add links to template documents re Grants/Contracts

- handbook/process/grant-program-rules.md
Current text says we use Wise, but we don't have a Wise account.
> Correct payment methods in grant program

- reports/BugTracker/maxwxyz_report.md
Update Bug Tracker Report 2024-05-15
> Update Bug Tracker Report 2024-05-15

- reports/BugTracker/maxwxyz_report.md
added bug tracker report for the last period
> Bug tracker report 2024-06-15

- reports/SketcherRefactor/ajinkya-report-may-june-2024.md
> Add report for Sketcher refactor May--June 2024

- handbook/process/bookkeeping/GrantsContractsVAT.md
adds a section and link re vat on banking fees.
> addition info re VAT & bank fees

- accounting/2024/contracts/contract_PHijma_VariantParts.md
add contract received from Pieter to  accounting/2024/contracts
> add variant parts contract - Hijma

- reports/BugTracker/maxwxyz_report.md
> Update 9: 2024-11-15

- reports/research-variant-parts/pieterhijma-2024-10.md
- reports/research-variant-parts/pieterhijma-2024-11.md
Adding reports for October and November
> Add reports "Research Variant Parts"

- reports/improve-c++-api-docs/pieterhijma-2024-11.md
> Add a report "Improve C++ API Documentation"

- handbook/process/logo.md
fixes https://github.com/FreeCAD/FreeCAD/issues/18080
> fix off black CMYK value

- reports/BugTracker/maxwxyz_report.md
> Update 10: 2024-12-15

- handbook/corporate/AISBL/fulltime_research.md
Started a research about what path it would take us to reach a stage where we could have full-time (or part-time) employees...
> Started full-time employee research

- code/annualReport/CommonDataHeader.csv
- code/annualReport/Python/commonAddCorporate.py
- code/annualReport/Python/gcExportAddPlatform.py
- code/annualReport/Python/gnuCashTxExportToCommonFormat.py
- code/annualReport/RScripts/DonationsByPlatform.r
- handbook/process/bookkeeping/AnnualReportStatistics.md
- handbook/process/bookkeeping/overview.md
some R & python scripts and documentation of some of the process.
> begin documentation of annual report process

- annualreports/2025.md
@chennes I just copied/pasted the 2025 top 4 from the agenda for now... Want to take care of that section?
@wandererfan Let's discuss what we want/need to put in the financial section (2024 and 2025) next FPA meeting?
> Started 2025 annual report

- annualreports/2025.md
Keeping the spirit of the original text, with some rephrasing for clarity and formality.
> Rephrase some of the Forward

- reports/improve-c++-api-docs/pieterhijma-2024-12.md
- reports/research-variant-parts/pieterhijma-2024-12.md
- Improve C++ API documentation
- Research Variant Parts
> Add Grant Proposal reports for December

- reports/#15 Documention/Evaluation of the Project with Roadmap Objectives.wikitext
I still can't make specific changes because I don't have the relevant information, but I can write a report. In this report, I declare, or rather manifest, the changes that the project plans to make regarding the objects in the roadmap. It was intended as a kind of vision document.
> (Grant #15)Report on Roadmap Objectives

- annualreports/2025.md
Update the numbers for spending forecast and VAT debt.
> Update spending forecast

- annualreports/2025.md
more numbers, different numbers, we have numbers,
> Update financial sections with latest numbers

- PRIVACY-POLICY.md
- index.md
Here we go! Please have a look @chennes @WandererFan @sliptonic
> Created privacy policy

- reports/#15 Documention/Final Report Dated June 14, 2025.wikitext
I’m proud to report that the wiki has now reached a highly acceptable and stable state. It’s no longer in a risky or fragile condition, and I believe it now offers a level of quality that few—if any—documentation platforms can match.
There may still be minor things I’ve overlooked. If you spot anything, feel free to point it out and I’ll gladly address it. As far as the grant milestones are concerned, I believe I’ve fulfilled the core technical objectives, and I’d like to request the remaining part of the funding.
My sister and I are going on a trip soon, and I wouldn’t mind having a bit more freedom to enjoy it generously :)
@yorikvanhavre — when you have a moment, could you take a look?
> (Grant #15)Final Report

- reports/improve-c++-api-docs/pieterhijma-2025-01.md
- reports/improve-c++-api-docs/pieterhijma-2025-02.md
- reports/improve-c++-api-docs/pieterhijma-2025-03.md
- reports/improve-c++-api-docs/pieterhijma-2025-04.md
- reports/improve-c++-api-docs/pieterhijma-2025-05.md
- reports/improve-c++-api-docs/pieterhijma-2025-06.md
- reports/improve-ux-varsets/pieterhijma-2025-01.md
- reports/improve-ux-varsets/pieterhijma-2025-02.md
- reports/improve-ux-varsets/pieterhijma-2025-03.md
- reports/improve-ux-varsets/pieterhijma-2025-04.md
- reports/improve-ux-varsets/pieterhijma-2025-05.md
- reports/improve-ux-varsets/pieterhijma-2025-06.md
- reports/occt-liaison/pieterhijma-2025-03.md
- reports/occt-liaison/pieterhijma-2025-04.md
- reports/occt-liaison/pieterhijma-2025-05.md
- reports/occt-liaison/pieterhijma-2025-06-25.md
- reports/research-variant-parts/pieterhijma-2025-01.md
- reports/research-variant-parts/pieterhijma-2025-02.md
These are currently reports for various projects and various months:
**Months**
- Jan
- Feb
- March
- April
- May
- June
**Projects**
- Improve C++ API documentation
- Research Variant Parts
- Improve User Experience VarSets
- OCCT Liaison
> Add reports

- reports/SketcherRefactor2/ajinkya-report-april-2025.md
More like a stub at the moment, but I just wanted to get something through for comments.
> Add report for Sketcher refactor December 2024--April 2025

- _includes/shortcuts.html
- assets/css/styles.scss
- index.md
- programs.md
> Fix homepage styling

- reports/CAM improvements for machining metals/leadinout dressup fixes and improvements.md
Added writeup for that sub-project (oops, I thought I submitted this PR a week ago)
> [CAM] Create leadinout dressup fixes and improvements.md

- handbook/process/bookkeeping/BNPTransactionProcessing.md
- handbook/process/bookkeeping/BNPTransactionProcessing.svg
bnp month end docs were out of date...
> update bnp month end process dox
